### ISSUE TITLE
FEATURE: Options to enable all of the features individually or moving them into separete plugins?

### ISSUE THREAD

**Issue by bit-ocean** [Ju99ernaut/grapesjs-plugin-toolbox#14]
Hi @Ju99ernaut !

There seems to be very interesting functionality in code you had wrote, yet I get the feeling that this plugin combines multiple features, and it is confusing to me how related they are to each other? Like there is the ability to generate palette from images, another is to add components with animated backgrounds, then rulers for the canvas, and a css grid system, and canvas resizer, and breadcrumbs... 

Maybe it could be split into separate plugins so users can choose what they need? I looked into the options and found that only some features can be toggled. Maybe it would be good enough just to be able to enable individually all of these features through the configuration options? I'm personally interested in the palette  feature.

Greetings!

**Comment by Ju99ernaut** [comment]
I can add a way to enable/disable any feature in the plugin, one of the main reasons I didn’t create separate plugins was because each feature is too small for its own plugin.
