### ISSUE TITLE
New grapes update breaks css-grid

### ISSUE THREAD

**Issue by anatoli-dp** [Ju99ernaut/grapesjs-plugin-toolbox#6]
New grapesjs update doesn't add css properties to grid when updating the grid from settings. Something to do with change in the css parser but idk what exactly. Issue arises when u call sel.components().reset(grid) in update command

**Comment by Ju99ernaut** [comment]
Yeah, something definitely up with the new update, I'll try see if there's an alternative API

**Comment by GaikwadShubham** [comment]
Hi @Ju99ernaut, I tried running the code but still it is giving me the same issues. The update, reset, toggle, clear tags are not working.

**Comment by Ju99ernaut** [comment]
Button traits currently aren't working https://github.com/artf/grapesjs/issues/3497

**Comment by GaikwadShubham** [comment]
Can you point out to a commit ID which I can use to run the application. Or do we have to wait for the bug to be resolved

**Comment by GaikwadShubham** [comment]
Can you point out to a commit ID which I can use to run the application. Or do we have to wait for the bug to be resolved

**Comment by Ju99ernaut** [comment]
I'm not really sure when it stopped working, the previous `grapesjs` version might work, but it will be fixed in the next release
