### ISSUE TITLE
Getting error while installing

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [Ju99ernaut/grapesjs-plugin-toolbox#7]
Hi @Ju99ernaut  Bro 
I've tried to integrate your plugin in my editor.
it's giving me error and also grid is not visible in the canvas
Could you please help me.Thanks
![Uploading Screenshot 2021-07-20 at 4.51.44 PM.png…]()

**Comment by Ju99ernaut** [comment]
I'm unable to view your screenshot.
