### ISSUE TITLE
Css grid layout tool doesn't work as expected

### ISSUE THREAD

**Issue by JakeMass** [Ju99ernaut/grapesjs-plugin-toolbox#8]
I installed the plugin in a laravel project and it seems to work correctly except the css grid layout tool.
I can draw my grid layout but when i click on update it creates the right amount of divs, but they do not have the right dimensions. They size down to one grid cell even though i want  them to span several rows and/or columns.
I noticed this behaviour in the demo also.

**Comment by Ju99ernaut** [comment]
It's probably broken due to an API change. I'll try look into it but I think it'll work on previous versions.
