### ISSUE TITLE
On reload, toolbar table is not working?

### ISSUE THREAD

**Issue by daud99** [Ju99ernaut/grapesjs-plugin-toolbox#9]
I did added the plugin and it's working as intended. But, when we reload the page. The grid component stay their as required as all the components are get stored in the local storage. However, when we click on the calendar table icon in the toolbar it does nothing. But if I delete all the component of grid and reload. And then drop new grid it works again.

In nutshell, it works only for the first time before any reload. Once you reload, already defined components nor does the newly drop grids none of them allow the use of toolbar option of selecting grid cells?

Traits does work.

How can I do this? If needed to customize the plugin what part I can customize?

**Comment by Ju99ernaut** [comment]
The table icon seems to be working fine even after reload so there might be an issue with storage, can you provide a demo reproducing the issue, however the issue I've noticed is that the grid layout template isn't being displayed after reload.

**Comment by Ju99ernaut** [comment]
I've managed to reproduce your issue in some cases so a demo won't be required anymore, I'll work on fixing both issues, thanks.
